spring.application.name=spring-config-example

spring.datasource.url=jdbc:postgresql://database:5432/demodb
spring.datasource.username=demouser
spring.datasource.password=demopassword
spring.jpa.hibernate.ddl-auto=none
